spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: house-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/house/**
        - id: agreement-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/agreement/**
        - id: payment-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/payment/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/micro-service"

server:
  port: 8222