spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      #      discovery:
      #        locator:
      #          enabled: true
      routes:
        - id: house-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/house/**
        - id: rental-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/rental/**
        - id: payment-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/payment/**
        - id: service-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/service/**
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/identity/**
        - id: notification-service
          uri: http://localhost:8040
          predicates:
            - Path=/api/v1/notification/**

server:
  port: 8222

app:
  api-prefix: /api/v1