server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
        bootstrap: true
        git:
          uri: https://github.com/fatthinh/house_rental_management.git

